displayName: "OIDC auth"
type: "middleware"
iconPath: ".github/icon.png"

import: "github.com/Yeicor/traefikgothauth"

summary: 'Multi-provider authentication plugin for Traefik, thanks to Goth.'

testData:
  Providers:
    - Name: "google"
      ClientKey: "YOUR_CLIENT_ID"
      ClientSecret: "YOUR_SECRET"
      RedirectURI: "https://yourdomain.com/__goth/google/"
    # More providers...
  CookieSecret: "ANY_PRIVATE_SECRET"
